create table post
(
    id bigint generated by default as identity,
    email varchar,
    password varchar,
    registration_date date,
    title  varchar,
    content  varchar,
    primary key (id)
)