drop table if exists item CASCADE;

create table post
(
    id bigint generated by default as identity,
    registration_date date,
    username varchar,
    title  varchar,
    content  varchar,
    primary key (id)
)

create table member
(
    id bigint generated by default as identity,
    email varchar,
    password varchar,
    username varchar,
    phone_number varchar,
    primary key (id)
)