drop table if exists item CASCADE;

create table post
(
    id bigint generated by default as identity,
    registration_date date,
    username varchar,
    title  varchar,
    content  varchar,
    primary key (id)
)

create type Role as enum ('USER', 'ADMIN');
create cast (character varying as role) with inout as assignment;

create table member
(
    id bigint generated by default as identity,
    email varchar unique,
    password varchar,
    username varchar,
    phone_number varchar,
    role Role,
    primary key (id)
)